-- Yoast SEO fields on WordPress-migrated content

ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "focusKeyword" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "ogTitle" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "ogDescription" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "ogImage" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "twitterTitle" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "twitterDescription" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "schemaJson" JSONB;

ALTER TABLE "SitePage" ADD COLUMN IF NOT EXISTS "focusKeyword" TEXT;
ALTER TABLE "SitePage" ADD COLUMN IF NOT EXISTS "ogTitle" TEXT;
ALTER TABLE "SitePage" ADD COLUMN IF NOT EXISTS "ogDescription" TEXT;
ALTER TABLE "SitePage" ADD COLUMN IF NOT EXISTS "ogImage" TEXT;
ALTER TABLE "SitePage" ADD COLUMN IF NOT EXISTS "twitterTitle" TEXT;
ALTER TABLE "SitePage" ADD COLUMN IF NOT EXISTS "twitterDescription" TEXT;
ALTER TABLE "SitePage" ADD COLUMN IF NOT EXISTS "schemaJson" JSONB;
