/**
 * Hostinger production build — standalone Next.js + launcher for panel start.
 * Panel: Build = npm run hostinger:build | Start = npm run hostinger:start
 */
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const frontendDir = path.join(repoRoot, 'apps', 'frontend');

const env = {
  ...process.env,
  HOSTINGER: '1',
  SKIP_WP_MEDIA_BUNDLE: '1',
};

function run(cmd, args) {
  const r = spawnSync(cmd, args, {
    cwd: repoRoot,
    stdio: 'inherit',
    shell: true,
    env,
  });
  if (r.status !== 0) process.exit(r.status ?? 1);
}

function findStandaloneServer(dir, depth = 0) {
  if (depth > 8 || !existsSync(dir)) return null;
  const direct = path.join(dir, 'server.js');
  if (existsSync(direct)) return direct;
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return null;
  }
  for (const name of entries) {
    if (name === 'node_modules') continue;
    const full = path.join(dir, name);
    try {
      if (statSync(full).isDirectory()) {
        const hit = findStandaloneServer(full, depth + 1);
        if (hit) return hit;
      }
    } catch {
      /* ignore */
    }
  }
  return null;
}

console.log('[hostinger-build] HOSTINGER=1 → next output: standalone');
run('npm', ['run', 'build:frontend']);

const standaloneRoot = path.join(frontendDir, '.next', 'standalone');
if (!existsSync(standaloneRoot)) {
  console.error('[hostinger-build] Missing apps/frontend/.next/standalone after build');
  process.exit(1);
}

const serverJs = findStandaloneServer(standaloneRoot);
if (!serverJs) {
  console.error('[hostinger-build] server.js not found under .next/standalone');
  process.exit(1);
}

const serverDir = path.dirname(serverJs);
const staticSrc = path.join(frontendDir, '.next', 'static');
const staticDest = path.join(serverDir, '.next', 'static');
const publicSrc = path.join(frontendDir, 'public');
const publicDest = path.join(serverDir, 'public');

if (existsSync(staticSrc)) {
  mkdirSync(path.dirname(staticDest), { recursive: true });
  cpSync(staticSrc, staticDest, { recursive: true });
  console.log('[hostinger-build] copied .next/static → standalone');
}

if (existsSync(publicSrc)) {
  cpSync(publicSrc, publicDest, { recursive: true });
  console.log('[hostinger-build] copied public → standalone');
}

// Relative path from apps/frontend/.next so Output-dir-only deploys still work
const relFromNext = path.relative(path.join(frontendDir, '.next'), serverJs).replace(/\\/g, '/');
const launcher = `#!/usr/bin/env node
// Auto-generated by hostinger-build — Hostinger requires listen() in THIS process (<3s).
const http = require('http');
const fs = require('fs');
const path = require('path');
const { parse } = require('url');

const serverJs = path.join(__dirname, ${JSON.stringify(relFromNext)});
const appDir = path.dirname(serverJs);
const port = parseInt(String(process.env.PORT || '3000'), 10);
const hostname = '0.0.0.0';

Object.assign(process.env, {
  PORT: String(port),
  HOSTNAME: hostname,
  HOSTINGER: '1',
  SKIP_WP_MEDIA_BUNDLE: '1',
  NODE_ENV: process.env.NODE_ENV || 'production',
});

let requestHandler = (req, res) => {
  res.statusCode = 503;
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.end('Starting…');
};

const server = http.createServer((req, res) => requestHandler(req, res));
server.listen(port, hostname, () => {
  console.log('[hostinger] listen() OK http://' + hostname + ':' + port);
});

(async () => {
  process.chdir(appDir);
  const requiredPath = path.join(appDir, '.next', 'required-server-files.json');
  if (fs.existsSync(requiredPath)) {
    const parsed = JSON.parse(fs.readFileSync(requiredPath, 'utf8'));
    process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(parsed.config || parsed);
  }
  const next = require(require.resolve('next', { paths: [appDir] }));
  const app = next({ dev: false, dir: appDir });
  await app.prepare();
  const handle = app.getRequestHandler();
  requestHandler = (req, res) => handle(req, res, parse(req.url || '/', true));
  console.log('[hostinger] Next.js handler ready', serverJs);
})().catch((err) => {
  console.error('[hostinger] boot failed', err);
  process.exit(1);
});
`;

writeFileSync(path.join(frontendDir, '.next', 'hostinger-server.cjs'), launcher);
writeFileSync(
  path.join(repoRoot, 'hostinger-server.cjs'),
  `#!/usr/bin/env node
require('./apps/frontend/.next/hostinger-server.cjs');
`
);

console.log('[hostinger-build] ready:', path.relative(repoRoot, serverJs));
console.log('[hostinger-build] start: npm run hostinger:start   OR   node hostinger-server.cjs');
