/**
 * Hostinger production build — standalone Next.js + launcher for panel start.
 * Panel: Build = npm run hostinger:build | Start = npm run hostinger:start
 */
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const frontendDir = path.join(repoRoot, 'apps', 'frontend');

const env = {
  ...process.env,
  HOSTINGER: '1',
  SKIP_WP_MEDIA_BUNDLE: '1',
};

function run(cmd, args) {
  const r = spawnSync(cmd, args, {
    cwd: repoRoot,
    stdio: 'inherit',
    shell: true,
    env,
  });
  if (r.status !== 0) process.exit(r.status ?? 1);
}

function findStandaloneServer(dir, depth = 0) {
  if (depth > 8 || !existsSync(dir)) return null;
  const direct = path.join(dir, 'server.js');
  if (existsSync(direct)) return direct;
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return null;
  }
  for (const name of entries) {
    if (name === 'node_modules') continue;
    const full = path.join(dir, name);
    try {
      if (statSync(full).isDirectory()) {
        const hit = findStandaloneServer(full, depth + 1);
        if (hit) return hit;
      }
    } catch {
      /* ignore */
    }
  }
  return null;
}

console.log('[hostinger-build] HOSTINGER=1 → next output: standalone');
run('npm', ['run', 'build:frontend']);

const standaloneRoot = path.join(frontendDir, '.next', 'standalone');
if (!existsSync(standaloneRoot)) {
  console.error('[hostinger-build] Missing apps/frontend/.next/standalone after build');
  process.exit(1);
}

const serverJs = findStandaloneServer(standaloneRoot);
if (!serverJs) {
  console.error('[hostinger-build] server.js not found under .next/standalone');
  process.exit(1);
}

const serverDir = path.dirname(serverJs);
const staticSrc = path.join(frontendDir, '.next', 'static');
const staticDest = path.join(serverDir, '.next', 'static');
const publicSrc = path.join(frontendDir, 'public');
const publicDest = path.join(serverDir, 'public');

if (existsSync(staticSrc)) {
  mkdirSync(path.dirname(staticDest), { recursive: true });
  cpSync(staticSrc, staticDest, { recursive: true });
  console.log('[hostinger-build] copied .next/static → standalone');
}

if (existsSync(publicSrc)) {
  cpSync(publicSrc, publicDest, { recursive: true });
  console.log('[hostinger-build] copied public → standalone');
}

// Relative path from apps/frontend/.next so Output-dir-only deploys still work
const relFromNext = path.relative(path.join(frontendDir, '.next'), serverJs).replace(/\\/g, '/');
const launcher = `#!/usr/bin/env node
// Auto-generated by hostinger-build — Hostinger requires listen() in THIS process (<3s).
// Fast path: disk static (public + _next/static) + in-memory HTML page cache.
const http = require('http');
const fs = require('fs');
const path = require('path');
const { parse } = require('url');

const serverJs = path.join(__dirname, ${JSON.stringify(relFromNext)});
const appDir = path.dirname(serverJs);
const port = parseInt(String(process.env.PORT || '3000'), 10);
const hostname = '0.0.0.0';

Object.assign(process.env, {
  PORT: String(port),
  HOSTNAME: hostname,
  HOSTINGER: '1',
  SKIP_WP_MEDIA_BUNDLE: '1',
  NODE_ENV: process.env.NODE_ENV || 'production',
});

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.avif': 'image/avif',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.otf': 'font/otf',
  '.txt': 'text/plain; charset=utf-8',
  '.xml': 'application/xml; charset=utf-8',
  '.webmanifest': 'application/manifest+json',
};

// Default 2 min in-memory HTML cache (set HTML_CACHE_TTL_MS=0 to disable).
const HTML_TTL_MS = Math.max(0, parseInt(process.env.HTML_CACHE_TTL_MS ?? '120000', 10) || 0);
const HTML_CACHE_MAX = Math.max(10, parseInt(process.env.HTML_CACHE_MAX || '80', 10) || 80);
const htmlCache = new Map();

function safeDecode(p) {
  try { return decodeURIComponent(p); } catch { return p; }
}

function underRoot(rootDir, filePath) {
  const rootResolved = path.resolve(rootDir);
  const resolved = path.resolve(filePath);
  const prefix = rootResolved.endsWith(path.sep) ? rootResolved : rootResolved + path.sep;
  return resolved === rootResolved || resolved.startsWith(prefix);
}

function cacheControlFor(filePath) {
  const base = path.basename(filePath).toLowerCase();
  if (base === 'sw.js') return 'no-cache, no-store, must-revalidate';
  // Disk path is .next/static (URL is /_next/static) - match both. No backticks here (breaks launcher template).
  const norm = String(filePath).split(String.fromCharCode(92)).join('/');
  if (norm.includes('/.next/static/') || norm.includes('/_next/static/') ||
      filePath.includes(path.sep + '_next' + path.sep + 'static' + path.sep)) {
    return 'public, max-age=31536000, immutable';
  }
  const ext = path.extname(filePath).toLowerCase();
  if (['.webp','.png','.jpg','.jpeg','.gif','.avif','.svg','.ico','.woff','.woff2','.ttf','.otf'].includes(ext)) {
    return 'public, max-age=31536000, immutable';
  }
  if (['.js','.css','.mjs'].includes(ext)) {
    return 'public, max-age=86400, stale-while-revalidate=604800';
  }
  return 'public, max-age=3600, stale-while-revalidate=86400';
}

function sendFile(req, res, filePath) {
  let st;
  try { st = fs.statSync(filePath); } catch { return false; }
  if (!st.isFile()) return false;
  const ext = path.extname(filePath).toLowerCase();
  const headers = {
    'Content-Type': MIME[ext] || 'application/octet-stream',
    'Content-Length': st.size,
    'Cache-Control': cacheControlFor(filePath),
    'Last-Modified': st.mtime.toUTCString(),
    'X-AR-Static': '1',
  };
  if (req.method === 'HEAD') { res.writeHead(200, headers); res.end(); return true; }
  res.writeHead(200, headers);
  fs.createReadStream(filePath).pipe(res);
  return true;
}

function tryServeStatic(req, res) {
  if (req.method !== 'GET' && req.method !== 'HEAD') return false;
  const { pathname: rawPath } = parse(req.url || '/', true);
  const pathname = safeDecode(rawPath || '/');
  if (!pathname || pathname === '/' || pathname.includes('\\0') || pathname.includes('..')) return false;
  if (pathname.startsWith('/api/')) return false;
  let filePath;
  if (pathname.startsWith('/_next/static/')) {
    filePath = path.join(appDir, '.next', 'static', pathname.slice('/_next/static/'.length));
    if (!underRoot(path.join(appDir, '.next', 'static'), filePath)) return false;
  } else {
    filePath = path.join(appDir, 'public', pathname);
    if (!underRoot(path.join(appDir, 'public'), filePath)) return false;
  }
  return sendFile(req, res, filePath);
}

function normalizeHtmlKey(pathname) {
  if (!pathname || pathname === '/') return '/';
  return pathname.replace(/\\/+$/, '') || '/';
}

function shouldCacheHtml(pathname, method) {
  if (!(HTML_TTL_MS > 0)) return false;
  if (method !== 'GET') return false;
  if (!pathname || pathname.startsWith('/api/') || pathname.startsWith('/_next/') || pathname.includes('.')) return false;
  return true;
}

function isCompressedBody(body, contentEncoding) {
  if (contentEncoding && String(contentEncoding).toLowerCase() !== 'identity') return true;
  if (!body || body.length < 2) return false;
  if (body[0] === 0x1f && body[1] === 0x8b) return true;
  return false;
}

function rememberHtml(key, statusCode, headers, body) {
  if (statusCode !== 200 || !body || !body.length) return;
  if (isCompressedBody(body, headers && headers['Content-Encoding'])) return;
  if (htmlCache.size >= HTML_CACHE_MAX) {
    const oldest = htmlCache.keys().next().value;
    if (oldest !== undefined) htmlCache.delete(oldest);
  }
  const outHeaders = Object.assign({}, headers);
  outHeaders['Cache-Control'] = outHeaders['Cache-Control'] || 'public, s-maxage=120, stale-while-revalidate=600';
  outHeaders['X-AR-Html-Cache'] = 'STORE';
  outHeaders['Content-Length'] = Buffer.byteLength(body);
  htmlCache.set(key, { expires: Date.now() + HTML_TTL_MS, statusCode, headers: outHeaders, body });
}

function tryServeHtmlCache(req, res) {
  if (req.method !== 'GET' && req.method !== 'HEAD') return false;
  const { pathname: rawPath } = parse(req.url || '/', true);
  const key = normalizeHtmlKey(safeDecode(rawPath || '/'));
  if (!shouldCacheHtml(key, 'GET')) return false;
  const hit = htmlCache.get(key);
  if (!hit || hit.expires <= Date.now()) {
    if (hit) htmlCache.delete(key);
    return false;
  }
  const headers = Object.assign({}, hit.headers, { 'X-AR-Html-Cache': 'HIT' });
  if (req.method === 'HEAD') { res.writeHead(hit.statusCode, headers); res.end(); return true; }
  res.writeHead(hit.statusCode, headers);
  res.end(hit.body);
  return true;
}

function wrapHtmlCache(handle) {
  return (req, res) => {
    if (tryServeStatic(req, res)) return;
    if (tryServeHtmlCache(req, res)) return;
    const { pathname: rawPath } = parse(req.url || '/', true);
    const key = normalizeHtmlKey(safeDecode(rawPath || '/'));
    if (!shouldCacheHtml(key, req.method || 'GET')) {
      return handle(req, res, parse(req.url || '/', true));
    }
    const chunks = [];
    let statusCode = 200;
    const headerBag = {};
    const origWriteHead = res.writeHead.bind(res);
    const origWrite = res.write.bind(res);
    const origEnd = res.end.bind(res);
    const origSetHeader = res.setHeader.bind(res);
    res.writeHead = function (code, reasonOrHeaders, maybeHeaders) {
      statusCode = typeof code === 'number' ? code : statusCode;
      let headers = maybeHeaders;
      if (typeof reasonOrHeaders === 'object' && reasonOrHeaders) headers = reasonOrHeaders;
      if (headers && typeof headers === 'object') {
        Object.keys(headers).forEach((k) => {
          const v = headers[k];
          headerBag[k.toLowerCase()] = Array.isArray(v) ? v.join(', ') : String(v);
        });
      }
      return origWriteHead(code, reasonOrHeaders, maybeHeaders);
    };
    res.setHeader = function (name, value) {
      headerBag[String(name).toLowerCase()] = Array.isArray(value) ? value.join(', ') : String(value);
      return origSetHeader(name, value);
    };
    res.write = function (chunk, encoding, cb) {
      if (chunk) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk, encoding));
      return origWrite(chunk, encoding, cb);
    };
    res.end = function (chunk, encoding, cb) {
      if (chunk) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk, encoding));
      const body = Buffer.concat(chunks);
      const ct = headerBag['content-type'] || '';
      const contentEncoding = headerBag['content-encoding'] || '';
      if (ct.includes('text/html') && statusCode === 200 && !headerBag['set-cookie'] && !isCompressedBody(body, contentEncoding)) {
        rememberHtml(key, statusCode, {
          'Content-Type': ct || 'text/html; charset=utf-8',
          'Cache-Control': headerBag['cache-control'] || 'public, s-maxage=120, stale-while-revalidate=600',
        }, body);
      }
      return origEnd(chunk, encoding, cb);
    };
    return handle(req, res, parse(req.url || '/', true));
  };
}

let requestHandler = (req, res) => {
  if (tryServeStatic(req, res)) return;
  res.statusCode = 503;
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.end('Starting…');
};

const server = http.createServer((req, res) => {
  try { requestHandler(req, res); } catch (err) {
    console.error('[hostinger] request error', err);
    if (!res.headersSent) { res.statusCode = 500; res.end('Internal Server Error'); }
  }
});
server.listen(port, hostname, () => {
  console.log('[hostinger] listen() OK http://' + hostname + ':' + port);
});

(async () => {
  process.chdir(appDir);
  const requiredPath = path.join(appDir, '.next', 'required-server-files.json');
  if (fs.existsSync(requiredPath)) {
    const parsed = JSON.parse(fs.readFileSync(requiredPath, 'utf8'));
    process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(parsed.config || parsed);
  }
  const next = require(require.resolve('next', { paths: [appDir] }));
  const app = next({ dev: false, dir: appDir });
  await app.prepare();
  const handle = app.getRequestHandler();
  requestHandler = wrapHtmlCache(handle);
  console.log('[hostinger] Next.js ready (static disk + HTML cache)', serverJs);
})().catch((err) => {
  console.error('[hostinger] boot failed', err);
  process.exit(1);
});
`;

writeFileSync(path.join(frontendDir, '.next', 'hostinger-server.cjs'), launcher);
writeFileSync(
  path.join(repoRoot, 'hostinger-server.cjs'),
  `#!/usr/bin/env node
require('./apps/frontend/.next/hostinger-server.cjs');
`
);

console.log('[hostinger-build] ready:', path.relative(repoRoot, serverJs));
console.log('[hostinger-build] start: npm run hostinger:start   OR   node hostinger-server.cjs');
